In [5]:
import os
datapath = "../../../datasets/covidDataset"
print(os.path.exists(datapath))

True


In [30]:
paths = [os.path.join(root, name) for root,dirs,files in os.walk(datapath, topdown=False) for name in files]
print(len(paths))
# labels = [d for root,dirs,files in os.walk(datapath, topdown=False) for name in files for d in dirs]
# print(len(labels))

2481
0


# solve: find labels from os.walk

In [39]:
# for root, dirs, files in os.walk(datapath):
#     for d in dirs:
#         for file in files:
#             print(os.path.join(d,file))

In [53]:
labels = [os.path.split(path)[0].split("/")[-1] for path in paths]
print(len(labels))

2481


In [55]:
print(paths[1500])
print(labels[1500])

../../../datasets/covidDataset/COVID/Covid (909).png
COVID


In [56]:
from keras import models, layers
import tensorflow as tf

In [61]:
initializer = tf.keras.initializers.Ones()
values = initializer(shape=(3, 3))

In [65]:
input_shape = (224, 224, 3)
input_layer = tf.keras.layers.Input(shape=input_shape)
second_layer = tf.keras.layers.Conv2D(
8, kernel_size=(3,3), kernel_initializer=initializer , activation='relu', input_shape=input_shape)(input_layer)

In [70]:
from keras import Model
intermediate_layer_model = Model(inputs=input_layer,
                                 outputs=second_layer)

In [72]:
out = intermediate_layer_model.predict(paths[1])
print(out.shape)

IndexError: list index out of range

In [69]:
print(second_layer[0])

KerasTensor(type_spec=TensorSpec(shape=(222, 222, 8), dtype=tf.float32, name=None), name='tf.__operators__.getitem/strided_slice:0', description="created by layer 'tf.__operators__.getitem'")


In [59]:
initializer = tf.keras.initializers.Ones()
values = initializer(shape=(3, 3))

In [60]:
print(values)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
